version: 2

models:
  - name: customers
    description: one record per customer
    columns:
      - name: customer_id
        description: primary key
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: this cleans up customer data
    columns:
      - name: customer_id
        description: primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: this cleans up order data
    columns:
      - name: order_id
        description: primary key
        tests:
          - unique
          - not_null
      - name: status
        description: order status can be one of five values
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        description: unique customer identitifier
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id
